export const country = [
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "India", label: "India" },
];

export const district = [
  { label: "Dhaka", value: "Dhaka" },
  { label: "Bagerhat", value: "Bagerhat" },
  { label: "Bandarban", value: "Bandarban" },
  { label: "Barguna", value: "Barguna" },
  { label: "Barishal", value: "Barishal" },
  { label: "Bhola", value: "Bhola" },
  { label: "Bogra", value: "Bogra" },
  { label: "Brahmanbaria", value: "Brahmanbaria" },
  { label: "Chandpur", value: "Chandpur" },
  { label: "Chapai Nawabganj", value: "Chapai Nawabganj" },
  { label: "Chattogram (Chittagong)", value: "Chattogram (Chittagong)" },
  { label: "Chuadanga", value: "Chuadanga" },
  { label: "Cox's Bazar", value: "Cox's Bazar" },
  { label: "Cumilla (Comilla)", value: "Cumilla (Comilla)" },
  { label: "Dinajpur", value: "Dinajpur" },
  { label: "Faridpur", value: "Faridpur" },
  { label: "Feni", value: "Feni" },
  { label: "Gaibandha", value: "Gaibandha" },
  { label: "Gazipur", value: "Gazipur" },
  { label: "Gopalganj", value: "Gopalganj" },
  { label: "Habiganj", value: "Habiganj" },
  { label: "Jamalpur", value: "Jamalpur" },
  { label: "Jashore (Jessore)", value: "Jashore (Jessore)" },
  { label: "Jhalokati", value: "Jhalokati" },
  { label: "Jhenaidah", value: "Jhenaidah" },
  { label: "Joypurhat", value: "Joypurhat" },
  { label: "Khagrachari", value: "Khagrachari" },
  { label: "Khulna", value: "Khulna" },
  { label: "Kishoreganj", value: "Kishoreganj" },
  { label: "Kurigram", value: "Kurigram" },
  { label: "Kushtia", value: "Kushtia" },
  { label: "Lakshmipur", value: "Lakshmipur" },
  { label: "Lalmonirhat", value: "Lalmonirhat" },
  { label: "Madaripur", value: "Madaripur" },
  { label: "Magura", value: "Magura" },
  { label: "Manikganj", value: "Manikganj" },
  { label: "Meherpur", value: "Meherpur" },
  { label: "Moulvibazar", value: "Moulvibazar" },
  { label: "Munshiganj", value: "Munshiganj" },
  { label: "Mymensingh", value: "Mymensingh" },
  { label: "Naogaon", value: "Naogaon" },
  { label: "Narail", value: "Narail" },
  { label: "Narayanganj", value: "Narayanganj" },
  { label: "Narsingdi", value: "Narsingdi" },
  { label: "Natore", value: "Natore" },
  { label: "Netrokona", value: "Netrokona" },
  { label: "Nilphamari", value: "Nilphamari" },
  { label: "Noakhali", value: "Noakhali" },
  { label: "Pabna", value: "Pabna" },
  { label: "Panchagarh", value: "Panchagarh" },
  { label: "Patuakhali", value: "Patuakhali" },
  { label: "Pirojpur", value: "Pirojpur" },
  { label: "Rajbari", value: "Rajbari" },
  { label: "Rajshahi", value: "Rajshahi" },
  { label: "Rangamati", value: "Rangamati" },
  { label: "Rangpur", value: "Rangpur" },
  { label: "Satkhira", value: "Satkhira" },
  { label: "Shariatpur", value: "Shariatpur" },
  { label: "Sherpur", value: "Sherpur" },
  { label: "Sirajganj", value: "Sirajganj" },
  { label: "Sunamganj", value: "Sunamganj" },
  { label: "Sylhet", value: "Sylhet" },
  { label: "Tangail", value: "Tangail" },
  { label: "Thakurgaon", value: "Thakurgaon" },
];
